// adapters/react/src/FluxFilesModal.tsx
import React, { useCallback, useEffect } from 'react';
import type { FluxFilesModalProps } from './types';
import { useFluxFiles } from './useFluxFiles';

const defaultOverlayStyle: React.CSSProperties = {
  position: 'fixed',
  inset: 0,
  background: 'rgba(0, 0, 0, 0.5)',
  zIndex: 99999,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
};

const defaultModalStyle: React.CSSProperties = {
  width: '90vw',
  maxWidth: '1200px',
  height: '85vh',
  background: '#fff',
  borderRadius: '8px',
  overflow: 'hidden',
  boxShadow: '0 25px 50px rgba(0, 0, 0, 0.25)',
};

/**
 * Modal wrapper for FluxFiles.
 *
 * Renders a fullscreen overlay with the file manager when `open` is true.
 *
 * @example
 * ```tsx
 * const [open, setOpen] = useState(false);
 *
 * <button onClick={() => setOpen(true)}>Pick file</button>
 *
 * <FluxFilesModal
 *   open={open}
 *   endpoint="https://files.example.com"
 *   token={jwt}
 *   onSelect={(file) => {
 *     console.log(file);
 *     setOpen(false);
 *   }}
 *   onClose={() => setOpen(false)}
 * />
 * ```
 */
export function FluxFilesModal({
  open,
  endpoint,
  token,
  disk,
  mode = 'picker',
  allowedTypes,
  maxSize,
  onSelect,
  onClose,
  onReady,
  onEvent,
  overlayClassName,
  modalClassName,
}: FluxFilesModalProps) {
  const handle = useFluxFiles({
    endpoint,
    token,
    disk,
    mode,
    allowedTypes,
    maxSize,
    onSelect,
    onClose,
    onReady,
    onEvent,
  });

  // Close on escape
  useEffect(() => {
    if (!open) return;

    function onKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        onClose?.();
      }
    }

    document.addEventListener('keydown', onKeyDown);
    return () => document.removeEventListener('keydown', onKeyDown);
  }, [open, onClose]);

  // Prevent body scroll when open
  useEffect(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = prev;
    };
  }, [open]);

  const handleOverlayClick = useCallback(
    (e: React.MouseEvent) => {
      if (e.target === e.currentTarget) {
        onClose?.();
      }
    },
    [onClose]
  );

  if (!open) return null;

  return (
    <div
      className={overlayClassName}
      style={overlayClassName ? undefined : defaultOverlayStyle}
      onClick={handleOverlayClick}
      role="dialog"
      aria-modal="true"
      aria-label="FluxFiles File Manager"
    >
      <div
        className={modalClassName}
        style={modalClassName ? undefined : defaultModalStyle}
      >
        <iframe
          ref={handle.iframeRef}
          src={handle.iframeSrc}
          style={{ width: '100%', height: '100%', border: 'none' }}
          allow="clipboard-write"
          title="FluxFiles File Manager"
        />
      </div>
    </div>
  );
}

// adapters/vue/src/FluxFilesModal.vue
<script setup lang="ts">
import { watch, onMounted, onUnmounted } from 'vue';
import { useFluxFiles } from './useFluxFiles';
import type { FluxFile, FluxEvent } from './types';

const props = withDefaults(defineProps<{
  open: boolean;
  endpoint: string;
  token: string;
  disk?: string;
  mode?: 'picker' | 'browser';
  allowedTypes?: string[] | null;
  maxSize?: number | null;
  locale?: string | null;
  overlayClass?: string;
  modalClass?: string;
}>(), {
  disk: 'local',
  mode: 'picker',
});

const emit = defineEmits<{
  select: [file: FluxFile];
  close: [];
  ready: [];
  event: [event: FluxEvent];
  'update:open': [value: boolean];
}>();

const handle = useFluxFiles({
  endpoint: props.endpoint,
  token: props.token,
  disk: props.disk,
  mode: props.mode,
  allowedTypes: props.allowedTypes,
  maxSize: props.maxSize,
  locale: props.locale,
  onSelect: (file) => emit('select', file),
  onClose: () => {
    emit('close');
    emit('update:open', false);
  },
  onReady: () => emit('ready'),
  onEvent: (event) => emit('event', event),
});

function onKeyDown(e: KeyboardEvent) {
  if (e.key === 'Escape') {
    emit('close');
    emit('update:open', false);
  }
}

function onOverlayClick(e: MouseEvent) {
  if (e.target === e.currentTarget) {
    emit('close');
    emit('update:open', false);
  }
}

let prevOverflow = '';

watch(() => props.open, (val) => {
  if (val) {
    prevOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    document.addEventListener('keydown', onKeyDown);
  } else {
    document.body.style.overflow = prevOverflow;
    document.removeEventListener('keydown', onKeyDown);
  }
});

onUnmounted(() => {
  document.body.style.overflow = prevOverflow;
  document.removeEventListener('keydown', onKeyDown);
});
</script>

<template>
  <Teleport to="body">
    <div
      v-if="open"
      :class="overlayClass"
      :style="overlayClass ? undefined : {
        position: 'fixed',
        inset: '0',
        background: 'rgba(0, 0, 0, 0.5)',
        zIndex: 99999,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      }"
      role="dialog"
      aria-modal="true"
      aria-label="FluxFiles File Manager"
      @click="onOverlayClick"
    >
      <div
        :class="modalClass"
        :style="modalClass ? undefined : {
          width: '90vw',
          maxWidth: '1200px',
          height: '85vh',
          background: '#fff',
          borderRadius: '8px',
          overflow: 'hidden',
          boxShadow: '0 25px 50px rgba(0, 0, 0, 0.25)',
        }"
      >
        <iframe
          :ref="(el) => { handle.iframeRef.value = el as HTMLIFrameElement | null }"
          :src="handle.iframeSrc.value"
          style="width: 100%; height: 100%; border: none"
          allow="clipboard-write"
          title="FluxFiles File Manager"
        />
      </div>
    </div>
  </Teleport>
</template>
