// packages/react/src/FluxFiles.tsx
import React, { forwardRef, useImperativeHandle } from 'react';
import type { FluxFilesProps, FluxFilesHandle } from './types';
import { useFluxFiles } from './useFluxFiles';

/**
 * Embedded FluxFiles file manager component.
 *
 * Renders an iframe inside a container div. Use `ref` to access command methods.
 *
 * @example
 * ```tsx
 * const ref = useRef<FluxFilesHandle>(null);
 *
 * <FluxFiles
 *   ref={ref}
 *   endpoint="https://files.example.com"
 *   token={jwt}
 *   disk="local"
 *   onSelect={(file) => console.log(file)}
 *   height="600px"
 * />
 *
 * // Programmatic control:
 * ref.current?.navigate('/uploads');
 * ref.current?.refresh();
 * ```
 */
export const FluxFiles = forwardRef<FluxFilesHandle, FluxFilesProps>(
  function FluxFiles(props, ref) {
    const {
      endpoint,
      token,
      disk,
      mode,
      multiple,
      allowedTypes,
      maxUploadMb,
      maxSize,
      maxFiles,
      width = '100%',
      height = '600px',
      className,
      style,
      onSelect,
      onClose,
      onReady,
      onEvent,
      onTokenRefresh,
    } = props;

    const handle = useFluxFiles({
      endpoint,
      token,
      disk,
      mode,
      multiple,
      allowedTypes,
      maxUploadMb,
      maxSize,
      maxFiles,
      onSelect,
      onClose,
      onReady,
      onEvent,
      onTokenRefresh,
    });

    useImperativeHandle(ref, () => ({
      command: handle.command,
      navigate: handle.navigate,
      setDisk: handle.setDisk,
      refresh: handle.refresh,
      search: handle.search,
      crossCopy: handle.crossCopy,
      crossMove: handle.crossMove,
      crop: handle.crop,
      aiTag: handle.aiTag,
      setLocale: handle.setLocale,
      updateToken: handle.updateToken,
      ready: handle.ready,
    }), [handle]);

    const containerStyle: React.CSSProperties = {
      width: typeof width === 'number' ? `${width}px` : width,
      height: typeof height === 'number' ? `${height}px` : height,
      ...style,
    };

    return (
      <div className={className} style={containerStyle}>
        <iframe
          ref={handle.iframeRef}
          src={handle.iframeSrc}
          style={{ width: '100%', height: '100%', border: 'none' }}
          allow="clipboard-write; fullscreen"
          allowFullScreen
          title="FluxFiles File Manager"
        />
      </div>
    );
  }
);

// packages/vue/src/FluxFiles.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useFluxFiles } from './useFluxFiles';
import type { FluxFile, FluxEvent, TokenRefreshHandler } from './types';

const props = withDefaults(defineProps<{
  endpoint: string;
  token: string;
  disk?: string;
  mode?: 'picker' | 'browser';
  multiple?: boolean;
  allowedTypes?: string[] | null;
  maxUploadMb?: number | null;
  maxSize?: number | null;
  maxFiles?: number | null;
  locale?: string | null;
  onTokenRefresh?: TokenRefreshHandler;
  width?: string | number;
  height?: string | number;
}>(), {
  disk: 'local',
  mode: 'picker',
  multiple: false,
  width: '100%',
  height: '600px',
});

const emit = defineEmits<{
  select: [file: FluxFile | FluxFile[]];
  close: [];
  ready: [];
  event: [event: FluxEvent];
}>();

const handle = useFluxFiles({
  endpoint: props.endpoint,
  token: props.token,
  disk: props.disk,
  mode: props.mode,
  multiple: props.multiple,
  allowedTypes: props.allowedTypes,
  maxUploadMb: props.maxUploadMb,
  maxSize: props.maxSize,
  maxFiles: props.maxFiles,
  locale: props.locale,
  onTokenRefresh: props.onTokenRefresh,
  onSelect: (file) => emit('select', file),
  onClose: () => emit('close'),
  onReady: () => emit('ready'),
  onEvent: (event) => emit('event', event),
});

const containerStyle = computed(() => ({
  width: typeof props.width === 'number' ? `${props.width}px` : props.width,
  height: typeof props.height === 'number' ? `${props.height}px` : props.height,
}));

defineExpose({
  command: handle.command,
  navigate: handle.navigate,
  setDisk: handle.setDisk,
  refresh: handle.refresh,
  search: handle.search,
  crossCopy: handle.crossCopy,
  crossMove: handle.crossMove,
  crop: handle.crop,
  aiTag: handle.aiTag,
  ready: handle.ready,
});
</script>

<template>
  <div :style="containerStyle">
    <iframe
      :ref="(el) => { handle.iframeRef.value = el as HTMLIFrameElement | null }"
      :src="handle.iframeSrc.value"
      style="width: 100%; height: 100%; border: none"
      allow="clipboard-write; fullscreen"
      allowfullscreen
      title="FluxFiles File Manager"
    />
  </div>
</template>
